version: '3.8'

services:
  wec-ca:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      - WECCA_ADDRESS=:8443
      - WECCA_HOSTNAME=acme.yourdomain.com
      - WECCA_DOMAIN=yourdomain.com
      - WECCA_SERVER_URL=https://acme.yourdomain.com:8443
      - WECCA_CERT_LIFETIME=720h  # 30 days
      - TZ=UTC
    volumes:
      - ./data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate --spider https://localhost:8443/acme/directory || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m